---
name: refresh
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - name: Commit user.name and email
        run: |
          git config --global user.email git@intermittent.energy
          git config --global user.name intermittent.energy
      - name: receive new files from SQS
        env:
          AWS_REGION: sa-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./receive.rb
